name: laundry_manager
description: "Gestión profesional del ciclo de vida de prendas de lavandería."
publish_to: "none"
version: 1.2.0+3

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.3.0
  riverpod_annotation: ^4.0.2
  hive_flutter: ^1.1.0
  go_router: ^14.2.7
  image_picker: ^1.1.2
  fpdart: ^1.1.0
  uuid: ^4.4.0
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  riverpod_generator: ^4.0.3
  build_runner: ^2.4.9
  mockito: ^5.4.4
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

